version: 0.2

phases:
  install:
    commands:
      - npm install --global gatsby-cli
      - npm install
      - pip install --upgrade awscli
  build:
    commands:
      - gatsby build
      - aws s3 sync _site/ s3://test-code-build